app/models.py
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.sql import func
import datetime
import uuid
import re

db = SQLAlchemy()


class Categories(db.Model):
    __tablename__ = 'categories'
    uuid = db.Column(db.String(20), primary_key=True,
                     default=lambda: uuid.uuid4().hex)
    name = db.Column(db.String(50), unique=True, nullable=False)
    created_at = db.Column(db.DateTime(timezone=True),
                           server_default=func.now())
    updated_at = db.Column(db.DateTime(timezone=True),
                           onupdate=func.now())
    items = db.relationship('Items', backref='category', lazy=True)


class Items(db.Model):
    __tablename__ = 'items'
    uuid = db.Column(db.String(20), primary_key=True,
                     default=lambda: uuid.uuid4().hex)
    name = db.Column(db.String(50), nullable=False)
    description = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime(timezone=True),
                           server_default=func.now())
    updated_at = db.Column(db.DateTime(timezone=True),
                           onupdate=func.now())
    category_id = db.Column(db.String, db.ForeignKey(
        'categories.uuid'), nullable=False)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, SelectField,\
    SubmitField
from wtforms.validators import DataRequired, Length, Email, Regexp
from wtforms import ValidationError
from models import Categories


class ItemForm(FlaskForm):
    name = StringField('Name', validators=[
                       DataRequired()])
    description = TextAreaField('Description', validators=[
                                DataRequired()])
    category = SelectField(
        u'Category')
    submit = SubmitField('Submit')

    def __init__(self, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        self.category.choices = [(category.uuid, category.name)
                                 for category in Categories.query.order_by('name').all()]

app/__init__.py
import os
from flask import Flask
from flask_wtf.csrf import CSRFProtect


def create_app(config_filename):
    app = Flask(__name__)
    cfg = os.path.join(os.getcwd(), 'config', config_filename + '.py')
    app.config.from_pyfile(cfg)

    from models import db
    db.init_app(app)

    from views import catalog_bp
    app.register_blueprint(catalog_bp, url_prefix='/')

    csrf = CSRFProtect()
    csrf.init_app(app)

    return app

app/views.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask import session as login_session
from models import db, Categories, Items
from sqlalchemy import and_
import re
import string
import random
from forms import ItemForm
from wtforms import ValidationError
from oauth2client.client import flow_from_clientsecrets
from oauth2client.client import FlowExchangeError
import httplib2
import json
from flask import make_response
import requests


catalog_bp = Blueprint('catalog', __name__)


@catalog_bp.route('/catalog/<string:category>/<string:item>')
@catalog_bp.route('/catalog/<string:category>/items')
@catalog_bp.route('/')
def root(category='default', item='default'):
    categories = Categories.query.order_by('name').all()
    if category == 'default':
        items = Items.query.order_by('created_at').all()
        return render_template('root.html', categories=categories, category='Latest', items=items)
    else:
        category = Categories.query.filter_by(name=category).first_or_404()
        if item == 'default':
            return render_template('root.html', categories=categories, category=category.name, items=category.items)
        else:
            item = Items.query.filter(and_(Items.name.like(
                item)), (Items.category_id.like(category.uuid))).first_or_404()
            return render_template('item_details.html', item=item)


@catalog_bp.route('/catalog/add', methods=['GET', 'POST'])
def add():
    form = ItemForm()
    if request.method == 'GET':
        return render_template('items.html', form=form)
    if form.validate_on_submit():
        category = Categories.query.filter_by(uuid=form.category.data).first()
        item = Items(name=form.name.data, description=form.description.data)
        item.category = category
        db.session.add(item)
        db.session.commit()
        return redirect(url_for('catalog.root'))
    else:
        errors = form.errors.items()
        for error in errors:
            message = "%(field)s - %(message)s" % ({
                'field': error[0],
                'message': error[1][0]
            })
            flash(message)
        return render_template('items.html', form=form)


@catalog_bp.route('/catalog/<string:category>/<string:item>/edit', methods=['GET', 'POST'])
def edit(category, item):
    category = Categories.query.filter_by(name=category).first_or_404()
    item = Items.query.filter(and_(Items.name.like(
        item)), (Items.category_id.like(category.uuid))).first_or_404()
    form = ItemForm()
    if request.method == 'GET':
        form.name.data = item.name
        form.description.data = item.description
        form.category.process_data(category.uuid)
        return render_template('items.html', form=form)
    if form.validate_on_submit():
        item.name = form.name.data
        item.description = form.description.data
        db.session.add(item)
        db.session.commit()
        return redirect(url_for('catalog.root'))
    else:
        errors = form.errors.items()
        for error in errors:
            message = "%(field)s - %(message)s" % ({
                'field': error[0],
                'message': error[1][0]
            })
            flash(message)
        return render_template('items.html', form=form)


@catalog_bp.route('/catalog/<string:category>/<string:item>/delete', methods=['GET', 'POST'])
def delete(category, item):
    form = ItemForm()
    if request.method == 'POST':
        category = Categories.query.filter_by(name=category).first_or_404()
        item = Items.query.filter(and_(Items.name.like(
            item)), (Items.category_id.like(category.uuid))).first_or_404()
        db.session.delete(item)
        db.session.commit()
        return redirect(url_for('catalog.root'))
    return render_template('delete.html', form=form)


@catalog_bp.route('/login')
def login():
    state = ''.join(random.choice(string.ascii_uppercase + string.digits)
                    for x in xrange(32))
    login_session['state'] = state
    print "Hello World"
    return render_template('login.html', STATE=state)

app/templates/delete.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title></title>
</head>

<body>
  <h1>Delete Item</h1>
  <form method="POST">
    {{ form.csrf_token }}
    <p> Are you sure you want to delete? </p>
    <input type="submit" value="Submit">
  </form>
</body>

</html>

app/templates/item_details.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>{{item.name}}</title>
</head>

<body>
  <h1>{{item.name}}</h1>
  <p> Description: {{item.description}}</p>
  <p> <a href="{{url_for('catalog.edit', category=item.category.name, item=item.name )}}"> Edit  </a> </p>
  <p> <a href="{{url_for('catalog.delete', category=item.category.name, item=item.name )}}"> Delete </a> </p>
</body>

</html>

app/templates/items.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Item</title>
</head>

<body>
  {% with messages = get_flashed_messages() %}
      {% if messages %}
      <ul>
        {% for message in messages %}
        <li><strong>{{message}}</strong></li>
        {% endfor %}
      </ul>
      {% endif %}
  {% endwith %}
  <form method="POST">
    {{ form.csrf_token }}
    {{ form.name.label }} <br>
    {{ form.name }} <br>
    {{ form.description.label }} <br>
    {{ form.description }} <br>
    {{form.category.label}} <br>
    {{ form.category()}} <br>
    <input type="submit">
  </form>
</body>

</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title> Login </title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>

<body>
  <div id="fb-root"></div>
  <div class="fb-login-button" data-max-rows="1" data-size="medium" data-button-type="login_with" data-show-faces="false" data-auto-logout-link="true" data-use-continue-as="true"></div>
  <script>
    function statusChangeCallback(response) {
      console.log('statusChangeCallback');
      console.log(response);
      // The response object is returned with a status field that lets the
      // app know the current login status of the person.
      // Full docs on the response object can be found in the documentation
      // for FB.getLoginStatus().
      if (response.status === 'connected') {
        // Logged into your app and Facebook.
        testAPI();
      } else {
        // The person is not logged into your app or we are unable to tell.
        document.getElementById('status').innerHTML = 'Please log ' +
          'into this app.';
      }
    }
    window.fbAsyncInit = function() {
      FB.init({
        appId: '247458079329853',
        autoLogAppEvents: true,
        xfbml: true,
        version: 'v3.0'
      });
      FB.getLoginStatus(function(response) {
        statusChangeCallback(response);
      });
    };

    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {
        return;
      }
      js = d.createElement(s);
      js.id = id;
      js.src = "https://connect.facebook.net/en_US/sdk.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    function testAPI() {
      console.log('Welcome!  Fetching your information.... ');
      FB.api('/me', function(response) {
        console.log('Successful login for: ' + response.name);
        document.getElementById('status').innerHTML =
          'Thanks for logging in, ' + response.name + '!';
      });
    }
  </script>

</body>

</html>

app/templates/root.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Catalog</title>
</head>
<body>
  <h1> Categories </h1>
  <ul>
  {% for category in categories %}
      <li><a href="{{url_for('catalog.root', category=category.name)}}">{{ category.name }}</a></li>
  {% endfor %}
  </ul>
  <h1> {{ category }} Items </h1>
  <p><a href="{{url_for('catalog.add')}}">Add Item</a></p>
  <ul>
  {% for item in items %}
      <li><a href="{{url_for('catalog.root', category=item.category.name, item=item.name)}}">{{ item.name }} ({{item.category.name}})</a></li>
  {% endfor %}
  </ul>
</body>
</html>